#// Nom : Slimani 
#// Prénom : Arezki
#// n° étudiant : 21502933
#// Petit test des familles



all: clean compil 

lancer: clean compil
	./test

compil: 
	clang++ test.cc -o test

clean:
	rm -f test



